require 'chart-js-rails'
require 'bootstrap-datepicker-rails'
require 'devise'
require 'delayed_job_active_record'
require 'cancancan'
require 'carrierwave-aws'
require 'coffee-rails'
require 'font-awesome-rails'
require 'fullcalendar-rails'
require 'icheck-rails'
require 'ionicons-rails'
require 'jquery-rails'
require 'jquery-fileupload-rails'
require 'jquery-ui-rails'
require 'jquery-datatables-rails'
require 'jquery-turbolinks'
require 'kaminari'
require 'less-rails-bootstrap'
require 'premailer/rails'
require 'pace/rails'
require 'momentjs-rails'
require 'sass-rails'
require 'slim-rails'
require 'turbolinks'
require "lowmac/engine"

module Lowmac
end
